apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse
spec:
  rules:
  - host: matrix.samcday.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synapse
            port:
              number: 8008
