apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  releaseName: vertical-pod-autoscaler
  chart:
    spec:
      # renovate: registryUrl=https://cowboysysop.github.io/charts/
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: kube-system
      version: 3.5.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml
  values:
    admissionController:
      resources: &resources
        requests:
          memory: 32Mi
      tolerations: &tolerations
        - key: CriticalAddonsOnly
          operator: Exists
    recommender:
      extraArgs:
        pod-recommendation-min-memory-mb: 32
      resources: *resources
      tolerations: *tolerations
    updater:
      extraArgs:
        # Allow VPA to update replica sets with only 1 replica. Means there will be downtime,
        # but if we're running stuff with only 1 replica it means we don't really care about uptime ;)
        min-replicas: 1
      resources: *resources
      tolerations: *tolerations
