apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  releaseName: sops-secrets-operator
  chart:
    spec:
      # renovate: registryUrl=https://isindir.github.io/sops-secrets-operator/
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: kube-system
      version: 0.9.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/isindir/sops-secrets-operator/blob/master/chart/helm3/sops-secrets-operator/values.yaml
  values:
    image:
      repository: isindir/sops-secrets-operator
      tag: 0.3.2
    secretsAsFiles:
      - name: age
        mountPath: /etc/age
        secretName: sops-age
    extraEnv:
      - name: SOPS_AGE_KEY_FILE
        value: /etc/age/age.agekey 
    # We want this thing to run on control plane.
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
