apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: autoscaler-cloud-init
spec:
    secretTemplates:
        - name: autoscaler-cloud-init
          stringData:
            data: ENC[AES256_GCM,data:sotfPFlq+O//bKmC2a1AJRfD0XV0aFDqM+zr6AgxxFmPUoAmO7e1FXbRTeCQ+D9qareI/1TVxKAjmi8dPjiUfDGJTUfXCkmLRZyoJvK4xYpP5Ne4X2nGWNlOrbrJ+83Ij0V6egtLVN4rGm9+gTVbVZMrXVNAAkAKjLfiyzRgwl5XaRFiRxLcXJUEG3vWdKWlYNNLFquI1YWISp3RjPEHJMTfNox+YKDUlwdDlVYW9isk4z240DdKUch9dcmYKXNO7hYYgiYsprlliqEzN+c5da2/CITBARuIt8+9xZEi9nnD6ZhsSWdk+3IgvCTk9L1rRKccUdarTpGy+Io8n9wPgdr0FAH82HTMwIIsMWE8OeyjhyQSdwDW7wBZNRxHIwXgL+gB7Kd0wQOhJc9FfKUGROxsGvAvCMHmcB/R/O6id9AZFxbEeGXDy5SLGaP4owGCni6dV4gIRI/hK8AYdxnaGQCnFES606g6,iv:8EPFhmRP1IegVT5jrKRCJJWK0SAGQ/2E3lIXaikhFus=,tag:tvOMraez9Hqpc/Aus+1ETA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzrnfrk2z0epqrtvqws5n9l8t2x5janyg9zamx74hksquvyfxgyqsuwz4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTHdQSk1Xck9WVDQ5RFF5
            bnRZT0UyWXo3Mi9iUUdtZENHb1hNeW5XMjA4CnhCS3lvTVlqQ0V0RkV0OWJtaEEv
            TXF3ZGpaWHUvRUhXUzhOWTZ0RGZocEUKLS0tIFNRcjJicDRqSEhUbzZxcUkwNEl2
            SUZmTThnRXlCRGlMMWlhSUZ5U1o5SWMKKsjQ07WrJIPHO1c39BHIKi0BhZCyQoRF
            1xunXREpSZ31fX9WOsZccCcVZ3zzbmAz1nXl6Y/kX7s/DSM17pw3Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cydkdqcsl9dzuze2uh65crllur9lkmfxcmew7w3us8cq87kcz39qc0yyhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2U0blh0US91WTJOQjFN
            MnhCdDRMTEh0bUlZWTBLSksxNzlBeEdXN2pNCnpEQVRlTlF2NlB3end6NWtnUGlj
            UlFSakRrRDZWVkdnSWlsMUwwT2h1Zm8KLS0tIGVIOFliVG1oZU1DUWdpUVUrOGo1
            VEhNeWxIVzcwR3NpQkd4S0xSQ0JGaWMKuKBlYGixy4+8COZfW/T5l52iqoxHUiYn
            7QxwZJEddVnvviwz+tFAor/0cAb7p3vzDwQxgOcFQSRT5JDc3npcrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-07-30T17:38:32Z"
    mac: ENC[AES256_GCM,data:WGMx10l+dnak94dx+5B20BT1lKZdyd+yZoAiZgvx9G69Hs9AUapyGkeoxlcNFNBwp6V/HIqZesING6m5Qwc9AqOSfpTj8KvkfMAlJRXwm1ofLpwh1p0OJXYK0g9Ig3ks+ONhGEwHNEKdqEuRUyYxqap0UjH8cNmLBA/cwZLKZGc=,iv:K3MNCaaPZSOiEh1W2vZF1L8FnMQoAgPu5mAE/+SpcJs=,tag:B99uOjALHmVHF8pOIOkQQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
