apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - release.yaml

secretGenerator:
  - name: autoscaler-cloud-init
    files:
    - data=cloud-init.txt

generatorOptions:
  disableNameSuffixHash: true
