apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cluster-autoscaler-hetzner-cluster-autoscaler
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cluster-autoscaler-hetzner-cluster-autoscaler
  updatePolicy:
    updateMode: Auto
