manager:
    secret:
        hcloudApiToken: ENC[AES256_GCM,data:vhiLXdcZ4nsWAzI6Q00zNhF6rf6HOUzHuvbkX5Tyd4NaWnh7pI3YJd7rVvjM0wc3wVX9g4/uvylPi8uF1cjHHg==,iv:IXVzcFtAHwNjkKYQz+mm2bG/5QTDw8dyPBaj4F+j60E=,tag:UXAZ0We8GEN5V6med8vqhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzrnfrk2z0epqrtvqws5n9l8t2x5janyg9zamx74hksquvyfxgyqsuwz4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ckNxS2dhWjVhZitqNDFl
            ZUFkdkxiYnlNdGZxYTdEZTBCZTJNMFVZY0hVCkFFT1dIZXFBSDNsOUdpK1hBQ1Ru
            WWp6R3JrUGRTVFd0M3ByUGdGOG5jQXcKLS0tIEtLUWx0dDNmYVNYeWhkM3YxaHRZ
            WnR5WmJtNGFnMmVoM2JIamJpVHhEWkUK8EfZ4SM63cCXb6xEHZzquphOAO/MP1zr
            OFYF9AoM4/AICWaxtsnJAykJoMbyGkVXbcM/Z7PdsVsYkf7vYhDOxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-07-24T19:48:09Z"
    mac: ENC[AES256_GCM,data:LsY4lus5FApWdG1qFOTppGr4rcovfePrKazaLQpAmHhe8/3mQ6mkisnIKZR/umZ1T1ktOlmz44JyLhSK7SQ2ZBmDooJ9WzCJ5fbBQav/PE+HzGwWbNRHEYma4ChN/FcuVaEgm4WgguvLlI4O9i80/YXgOqVPzaY6RHzK82u6ZLE=,iv:rSTjEAYFigcYhjM9nD0ZzsgWJAudYbMW+x+aNAGzQV8=,tag:UJkxwGW282ZQ4455spcq0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
