apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: backblaze-credentials
spec:
    secretTemplates:
        - name: backblaze-credentials
          stringData:
            cloud: ENC[AES256_GCM,data:X5iLn4qEFpI7vmB1APLolTaAcjq4FFT7rAWs5/smUd2XiedU2vctdQAkB/mFHasudXZkp2on8W+0lPVU6lwC8ZSzxYsiss9rEZiZy9NjTY+EPjJmAFQrJHWbWKFpRWe/BsHV5o4/ECcBylw=,iv:mavjtrzKfIs6k6toD0/Ht1Q+eFV2dRO3MPtJZSVGxtQ=,tag:BS5ZsuVLk4rkRwDiykicBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cydkdqcsl9dzuze2uh65crllur9lkmfxcmew7w3us8cq87kcz39qc0yyhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bEp3cXdIOTh5Uk9rcDhU
            OE5oRmVNRThSY29uQVd6cU1DT2gxdnFRb3drCkZVK2hlVkMyeEFkQ3BaRVpWTVJT
            RWx6RHJVVEZ3eEkvT0RmNnZ5L0dGclUKLS0tIEJoTHFNSjhZNE9qczVHS3VhWTh6
            V05rMis5MXJGOFpLZGpXdjZXVnpjVjAKWGGcMkMew7wIh6Gi7Vqj4LfVt2s8S0tR
            +tmluiPe/9WWWrwSAbz5rWowwBeeE4l84O93ShQ+5IolI1grCvObdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jzrnfrk2z0epqrtvqws5n9l8t2x5janyg9zamx74hksquvyfxgyqsuwz4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SklXK2RJVis1UGJiVGlr
            ZmJZMk5CY3JnUmRrL1JCY3BZUjJVSWQvR2dFCjBBemxleGppclk1TER6bTZyb1NJ
            RDlCSnNPV3RJL0daNHJabk1Pc2FudEUKLS0tIGYwRXdPSS8zTkVqbXovQ3Q3YXR6
            dDdhRFRFTWQwdDNBRktLSDJkOUo4bm8KR1+q+APSgXBA0/+JCYOKMnxlRT1j358H
            69tGr0J1QIPo/Gm+HeDHpb6ThR+sYW6WRgRFZedXrjaLFty7noUlFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-07-31T12:57:51Z"
    mac: ENC[AES256_GCM,data:Ya2B1S50o9kQowJzok/ZCi4kSRsMco206Qhed7yE7KspKEm5BuZebGj+tI+viEYBjfooNDFFn1dp75Pqre8EMrKnyCcjSB606/r9MdytEcifxntgva5gqESQTmrgzWMXSb4bjvB7w1ATfyuyew4APi1vhFTj1r0DioBFgjuaELI=,iv:O43Rm0J5kjkDRe7AmsclasbQSZEgD4jviPc2Ov5MmJM=,tag:0I6rUSFkf/sbzWqrik0TBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
