apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 2.23.5
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  interval: 1h
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
  values:
    deployRestic: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.2.0
      volumeMounts:
      - mountPath: /target
        name: plugins
    credentials:
      existingSecret: backblaze-credentials
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: samcday-cluster-backups
        prefix: cluster
        config:
          region: eu-central-003
          s3Url: https://s3.eu-central-003.backblazeb2.com
      volumeSnapshotLocation:
        name: default
        bucket: samcday-cluster-backups
        config:
          region: eu-central-003
          s3Url: https://s3.eu-central-003.backblazeb2.com
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      requests:
        memory: 128m
    restic:
      resources:
        requests:
          memory: 128m
