---
- hosts: all
  tasks:
    # Basic home user + shell setup.
    - name: install zsh
      apt:
        name: zsh
        state: present
    - name: create sam user
      user:
        name: sam
        shell: /usr/bin/zsh
        groups: sudo
        create_home: yes
    - name: add sam authorized_key
      authorized_key:
        user: sam
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDImwbiygRvd4DSdq8WrAJuVgbIhK67Dy86G3t3/g4Xxhs72AWB83dz2lgi/9qBA6pELKe0chh4RPZmPsaCR24zrstaqond4JCrdJxSV+Fgk4t8O6jmS5siPYnIUyAbaUTxdkLmnJNEya2Svp5E4woTKtME1mXm4FBiyc9ZV6oFJ5oc7y3XTcgYhudGI2RzV7tquC0fpuV4RzIPclSEw9ITQvQFqSdqZfOhraGhr1nu2YUGJtAdks6Gusl65UYCwkwpuCH0SDFen1yk/JklkY7jH6qm15aJFQPcn/I/oNUsFRQ3TE0e2n5OnV7rx8QQSQx+mquXj+8VQYWU0WHhijyZ"

    # Wireguard bridge interface + configuration.
    - name: install wireguard-tools
      apt:
        name: wireguard-tools
        state: present
    - name: create wg0 interface
      command:
        cmd: ip link add dev wg0 type wireguard
        creates: /sys/class/net/wg0
    - name: configure wg0 address
      command: ip addr replace dev wg0 192.168.250.1/24
    - name: put Wireguard private key in place
      copy:
        content: '{{ wireguard_private_key }}'
        dest: /etc/wg0-private-key
        mode: 0600
    - name: setup Wireguard
      command: wg set wg0 listen-port 51820 private-key /etc/wg0-private-key peer 82xSogfNwqdBHJFmV4uliwN6s0GVXwfCKZW9URrM2Aw= allowed-ips 192.168.250.2/32
    - name: bring up wg0 interface
      command: ip link set up wg0
- name: Include kubespray tasks
  import_playbook: kubespray/cluster.yml
