apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hcloud-csi.yaml
patches:
  - target:
      kind: StatefulSet
      name: hcloud-csi-controller
    path: ss-patch.yaml
  - target:
      kind: DaemonSet
      name: hcloud-csi-node
    path: ds-patch.yaml
