- op: replace
  path: /spec/template/spec/containers/3/env/3/valueFrom/secretKeyRef/name
  value: hcloud
- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: CriticalAddonsOnly
      operator: Exists
