apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hcloud-csi-node
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: hcloud-csi-node
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hcloud-csi-controller
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hcloud-csi-controller
  updatePolicy:
    updateMode: Auto
