apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - mongodb-password-sops-secret.yaml
  - mongodb.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: wekanteam/wekan
    newTag: v5.41
