apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
data:
  log.yaml: |
    version: 1
    formatters:
      json:
        class: synapse.logging.TerseJsonFormatter
    handlers:
      stdout:
        class: logging.StreamHandler
        formatter: json
    root:
      level: INFO
      handlers: [stdout]
