apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: synapse
  name: synapse
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: synapse-media
      labels:
        app.kubernetes.io/name: synapse
    spec:
      initContainers:
      - name: setup-dbconfig
        image: busybox:1.33.1
        command:
        - sh
        - '-c'
        - |-
          ls /dbcreds && \
          cat /dbcreds/password && \
          cp /homeserver-config/homeserver.yaml /generated-config/homeserver.yaml && \
          echo "database:" >> /generated-config/homeserver.yaml && \
          echo "  name: psycopg2" >> /generated-config/homeserver.yaml && \
          echo "  args:" >> /generated-config/homeserver.yaml && \
          echo "    user: $(cat /dbcreds/user)" >> /generated-config/homeserver.yaml && \
          echo "    password: $(cat /dbcreds/password)" >> /generated-config/homeserver.yaml && \
          echo "    host: $(cat /dbcreds/host)" >> /generated-config/homeserver.yaml && \
          echo "    port: $(cat /dbcreds/port)" >> /generated-config/homeserver.yaml && \
          echo "    cp_min: 5" >> /generated-config/homeserver.yaml && \
          echo "    cp_min: 10" >> /generated-config/homeserver.yaml
        volumeMounts:
        - name: homeserver-config
          mountPath: /homeserver-config
          readOnly: true
        - name: dbcreds
          mountPath: /dbcreds
          readOnly: true
        - name: synapse-media
          mountPath: /media
        - name: generated-config
          mountPath: /generated-config
      containers:
      - name: synapse
        image: matrixdotorg/synapse:v1.38.1
        env:
        - name: SYNAPSE_CONFIG_PATH
          value: /generated-config/homeserver.yaml
        livenessProbe:
          httpGet:
            path: /health
            port: 8008
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: dbcreds
          mountPath: /dbcreds
          readOnly: true
        - name: synapse-media
          mountPath: /media
        - name: generated-config
          mountPath: /generated-config
      volumes:
      - name: dbcreds
        secret:
          secretName: synapse-pguser
      - name: config
        configMap:
          name: synapse-config
      - name: homeserver-config
        secret:
          secretName: synapse-homeserver-config
      - name: synapse-media
        persistentVolumeClaim:
          claimName: synapse-media
      - name: generated-config
        emptyDir: {}
