apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - config.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - homeserver-config-sops-secret.yaml
  - ingress.yaml
