apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: synapse
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-0
  postgresVersion: 13
  instances:
    - name: instance1
      replicas: 1
      resources:
        requests:
          memory: 128Mi
        limits:
          memory: 256Mi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 30Gi
        storageClassName: hcloud-volumes
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
      repoHost:
        dedicated: {}
      global:
        repo1-path: /pgbackrest/default/synapse
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: "@weekly"
          differential: "@daily"
          incremental: "@hourly"
        s3:
          bucket: samcday-pgo
          endpoint: s3.eu-central-003.backblazeb2.com
          region: eu-central-003
      configuration:
      - secret:
          name: pgo-s3-creds
      manual:
        repoName: repo1
        options:
         - --type=full
