apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
spec:
  selector:
    app.kubernetes.io/name: synapse
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 9000
