apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: synapse
spec:
  endpoints:
  - port: metrics
    interval: 15s
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
