apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: synapse-db
spec:
  teamId: synapse
  volume:
    size: 20Gi
    storageClass: hcloud-volumes
  numberOfInstances: 1
  users:
    synapse:
    - superuser
    - createdb
  databases:
    synapse: synapse
  postgresql:
    version: "13"
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "C"
