---
- name: create restic user
  user:
    name: restic
    shell: /usr/sbin/nologin
    create_home: yes

- name: create paths
  file:
    path: '/home/restic/{{ item }}'
    state: directory
    owner: restic
  loop: [.ssh, bin]

- name: make sure bzip2 is installed lol
  apt:
    name: bzip2
    state: present

- name: grab restic binary
  shell:
    cmd: curl --retry 3 --fail -L https://github.com/restic/restic/releases/download/v0.9.6/restic_0.9.6_linux_amd64.bz2 | bunzip2 > ~restic/bin/restic
    creates: /home/restic/bin/restic

- name: setup correct ownership/mode on restic binary
  file:
    path: /home/restic/bin/restic
    mode: 0750
    group: restic
    owner: root

- name: set cap_dac_read_search cap on restic binary
  capabilities:
    capability: cap_dac_read_search=+ep
    path: /home/restic/bin/restic

- name: generate ssh creds
  openssh_keypair:
    type: ed25519
    path: /home/restic/.ssh/id_ed25519
    owner: restic
    mode: 0600

- name: setup ssh config
  copy:
    dest: /home/restic/.ssh/config
    content: |
      Host backup
        Hostname u243008.your-storagebox.de
        User u243008
        Port 23
        ServerAliveInterval 60
        ServerAliveCountMax 240

- name: import storage box known host
  shell:
    cmd: |
      ssh-keyscan u243008.your-storagebox.de -p 23 > ~restic/.ssh/known_hosts
      chown restic ~restic/.ssh/known_hosts
    creates: /home/restic/.ssh/known_hosts

- name: setup restic-repo password file
  copy:
    content: '{{ restic_repo_password }}'
    dest: /home/restic/.repopass
    mode: 0600
    owner: restic
