apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: kube-system
spec:
  dependsOn:
    - name: sops-secrets-operator
    - name: vertical-pod-autoscaler
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/external-dns
  prune: true
  validation: client
