apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: letsencrypt-issuers
  namespace: kube-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/letsencrypt-issuers
  prune: true
  validation: client
