apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: loki
  namespace: kube-system
spec:
  dependsOn:
    - name: vertical-pod-autoscaler
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/loki
  prune: true
  validation: client
