apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - github.com/mongodb/mongodb-kubernetes-operator/config/crd?ref=v0.7.0
  - github.com/mongodb/mongodb-kubernetes-operator/config/manager?ref=v0.7.0
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
images:
  - name: quay.io/mongodb/mongodb-kubernetes-operator
    newTag: 0.7.0
patches:
  - target:
      kind: Deployment
      name: mongodb-kubernetes-operator
    path: patches/watch_all_namespaces.yaml
