apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: kube-system
spec:
  dependsOn:
    - name: vertical-pod-autoscaler
    - name: sops-secrets-operator
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./cluster/infrastructure
  prune: true
  validation: client
