apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  dependsOn:
    - vertical-pod-autoscaler
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./cluster/infrastructure/sops-secrets-operator
  prune: true
  validation: client
