apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./cluster/infrastructure/vertical-pod-autoscaler
  prune: true
  validation: client
