apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: kube-system
  interval: 1h
  # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
  values:
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
