apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: promtail
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: promtail
  updatePolicy:
    updateMode: Auto
