apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-cloud-api-key
spec:
    secretTemplates:
        - name: grafana-cloud-api-key
          stringData:
            username: ENC[AES256_GCM,data:kpaSdpcerw==,iv:/kjj9LTj0NPFEuXCZooV7SuZbBzPD5CM1Yi3pfVJnAM=,tag:76M16+jIocZ7XCC8PosKNA==,type:str]
            password: ENC[AES256_GCM,data:4DuhtU4OEi5c0XuHD87mKF9Ep342cntrmQ0bfrC3VorzEqiPUyt/6Ecn5yBoODSItapkwbGWdvmojqgf6460XGSn/UWgN0DeD1B+8ynJq3q9Nzz1oeGwJSI0Ciw4DUEzpmHOupb4ACKCPI1NXCH0BZLEJFc=,iv:Nj1mh84IZNTR4Af2jCV6FeIWLuGUaeS0DWp8WaauzMA=,tag:EkTFTgrlLr1x9T8zhkULBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cydkdqcsl9dzuze2uh65crllur9lkmfxcmew7w3us8cq87kcz39qc0yyhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZzJkYTcvek44V3NZZ0VH
            OThhVnFxZTBiN1E1dFIwRHBGcjRkTXJTb2lBCnFPSUl1VWhzU3QycStoM3ZrREhH
            b1ZmSlFJUFFHcVFyWFhJMnZnN256QW8KLS0tIFh5V1Y3eWJYQTFKeFhhZVFTNmZs
            ZnRnN2cxVE1MNjE0ZXNmbWh2UUVkeUUKpJ8imsWXxM4XoR+D7aea0U4OWYrc7cS/
            sUzKasYlJlNQHuMUFqdi/NrF/H1G1RmkT6oMHMIlnj6NYGSkFQDDQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jzrnfrk2z0epqrtvqws5n9l8t2x5janyg9zamx74hksquvyfxgyqsuwz4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOElmVTFQZHE1TzQ2QVFh
            cmtxZnRVK0VGN1JoYVRMdHpoeEI5cWlhVEVZCkd5Y21wY2JEM2Fyd3JoT0hlNnMw
            dFZLUkEvbnFZb1M3M1FCVDNMQ0NWR2cKLS0tIGhwV2pSQUhvY1BTR3lJZUF2Y3Jw
            Vkc5VFdCUlhEb2NIZSszeGovUEZFQUUK0dEt3isrn9Sd8JYOe46o+a3XELeCPNtz
            Xn1e623hrm621ffTPTmQU86dEsxYSxh4vwulvvB+0KOzEvgLZoD2JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-08-09T11:28:07Z"
    mac: ENC[AES256_GCM,data:qEwEzN+VWTi3Remag2J2eDKas1wpUmtnfS8mRcWUCIa8UgLvj4wdYQxSy4IJf1DAsNIyRHEcWiNlytRaBVLWPcn7wWGwta5yUKQTGr1ZRra3gDACGOOvulVXQfq/OkUSeFGdDSZ/Vt4omivD9ZmVaa05nKTonvDcLw/+FKvez4g=,iv:0NESAxl3eecHfsz4w1D6nWTleVzlOChE7kB3UeiWYe4=,tag:1mYGuQBWLH14BpDVIKVd6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
