apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: zalando-pgo
  namespace: kube-system
spec:
  interval: 30m
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
