apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-kube-prometheus-stack-prometheus
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-prometheus-stack-grafana
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-prometheus-stack-prometheus-node-exporter
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: kube-prometheus-stack-prometheus-node-exporter
  updatePolicy:
    updateMode: Auto
