apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  interval: 30m
  url: https://isindir.github.io/sops-secrets-operator/
