apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.4.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-system
  interval: 1h0m0s
  timeout: 1m
  install:
    remediation:
      retries: 3
  # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.4.2
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.4.2
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.4.2
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
