apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kube-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
      image:
        repository: quay.io/prometheus/alertmanager
        tag: v0.22.2
    kubeEtcd:
      enabled: false
    kubeScheduler:
      endpoints: [10.0.0.2]
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
    prometheus-node-exporter:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
    prometheusOperator:
      admissionWebhooks:
        patch:
          image:
            repository: jettech/kube-webhook-certgen
            tag: v1.5.2
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.49.0
      prometheusConfigReloaderImage:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: v0.49.0
    prometheus:
      prometheusSpec:
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.28.1
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: hcloud-volumes
              accessModes: [ReadWriteOnce]
              resources:
                requests:
                  storage: 50Gi
