---
# Source: invidious/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: RELEASE-NAME-invidious
  labels:
    app: invidious
    chart: "invidious-1.1.0"
    release: RELEASE-NAME
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: RELEASE-NAME-invidious
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 50
