apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: kube-system
  interval: 1h
  # https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
  values:
    image:
      repository: grafana/loki
      tag: 2.2.1
    persistence:
      enabled: true
      storageClassName: hcloud-volumes
    serviceMonitor:
      enabled: true
