apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: loki
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: loki
  updatePolicy:
    updateMode: Auto
