repositories:
- name: zalando
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
- name: mlohr
  url: https://helm-charts.mlohr.com/
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: hcloud-controller
  chart: mlohr/hcloud-cloud-controller-manager
  version: 2.4.1
  values:
  - manager:
      secret:
        create: true
      privateNetwork:
        enabled: true
        id: infra
        clusterSubnet: 10.233.255.0/24

  secrets:
  - secrets/hcloud-controller.yaml

- name: hcloud-csi-driver
  chart: mlohr/hcloud-csi-driver
  version: 1.1.3
  values:
  - csiDriver:
      secret:
        create: yes
  secrets:
  - secrets/hcloud-csi-driver.yaml

- name: pgo-config
  chart: ./charts/pgo-config
  values:
  - endpoint: https://s3.eu-central-003.backblazeb2.com
  secrets:
  - secrets/pgo-config.yaml

- name: postgres-operator
  chart: zalando/postgres-operator
  version: 1.6.3
  values:
  - configKubernetes:
      enable_pod_disruption_budget: "false"
      pod_environment_configmap: default/postgres-pod-config
      pod_environment_secret: postgres-pod-secrets
  - configAwsOrGcp:
      aws_region: eu-central-003
      wal_s3_bucket: samcday-pgo

- name: grafana-agent
  chart: ./charts/grafana-agent
  values:
  - username: '166507'
  secrets:
  - secrets/grafana-agent.yaml

- name: node-exporter
  chart: prometheus-community/prometheus-node-exporter
  version: 2.0.1
  values:
  - prometheus:
      monitor:
        enabled: yes
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      operator: Exists

- name: kube-state-metrics
  chart: prometheus-community/kube-state-metrics
  version: 3.4.1
  values:
  - prometheus:
      monitor:
        enabled: yes

- name: synapse
  chart: ./charts/synapse
  secrets:
  - secrets/synapse.yaml
