repositories:
- name: zalando
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

- name: mlohr
  url: https://helm-charts.mlohr.com/

releases:
  - name: postgres-operator
    chart: zalando/postgres-operator
    version: 1.6.3

  - name: hcloud-csi-driver
    chart: mlohr/hcloud-csi-driver
    version: 1.1.3
    values:
      - csiDriver:
          secret:
            create: yes
    secrets:
      - secrets/hcloud-csi-driver.yaml

  - name: grafana-agent
    chart: ./charts/grafana-agent
    values:
      - username: '166507'
    secrets:
      - secrets/grafana-agent.yaml
