repositories:
- name: stable
  url: https://charts.helm.sh/stable

- name: mlohr
  url: https://helm-charts.mlohr.com/

releases:
  - name: postgres-operator
    namespace: postgres-operator
    chart: ./charts/postgres-operator

  - name: hcloud-csi-driver
    namespace: kube-system
    chart: mlohr/hcloud-csi-driver
    version: 1.1.3
    values:
      - csiDriver:
          secret:
            create: yes
    secrets:
      - secrets/hcloud-csi-driver.yaml
