apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  releaseName: vertical-pod-autoscaler
  chart:
    spec:
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: kube-system
      version: 3.5.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/values.yaml
  values:
    admissionController:
      tolerations: &tolerations
        - key: CriticalAddonsOnly
          operator: Exists
    recommender:
      tolerations: *tolerations
    updater:
      tolerations: *tolerations
