apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent
  namespace: default
  labels:
    app: grafana-agent
spec:
  image: grafana/agent:v0.17.0
  logLevel: info
  serviceAccountName: grafana-agent
  prometheus:
    instanceSelector:
      matchLabels:
        agent: grafana-agent
