apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wekan
  name: wekan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wekan
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wekan
    spec:
      containers:
      - name: wekan
        image: wekanteam/wekan:v5.41
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: wekan-mongodb-wekan-wekan
              key: connectionString.standard
        - name: ROOT_URL
          value: https://wekan.samcday.com
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
