apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wekan
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - wekan.samcday.com
    secretName: wekan-tls
  rules:
  - host: wekan.samcday.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wekan
            port:
              number: 80
