---
- name: install wireguard-tools
  apt:
    name: wireguard-tools
    state: present
- name: configure wg0 wg-quick config.
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600
  notify: [restart wg-quick@wg0.service]
- name:
  systemd:
    name: wg-quick@wg0.service
    enabled: yes
    state: started
