name: Annotate Flux Helm releases
on: [push]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: k8s-at-home/renovate-helm-releases@v1
        with:
          debug: 'yes'
          cluster-path: './'
          exclude-folders:
            - ./old
            - ./control-plane

