apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - hcloud-csi.yaml
  - vpa.yaml
patches:
  - target:
      kind: StatefulSet
      name: hcloud-csi-controller
    path: ss-patch.yaml
  - target:
      kind: DaemonSet
      name: hcloud-csi-node
    path: ds-patch.yaml
images:
  - name: quay.io/k8scsi/csi-attacher
    newTag: v3.1.0
  - name: quay.io/k8scsi/csi-resizer
    newTag: v0.5.1
  - name: quay.io/k8scsi/csi-provisioner
    newTag: v1.6.1
  - name: hetznercloud/hcloud-csi-driver
    newTag: 1.5.3
  - name: quay.io/k8scsi/livenessprobe
    newTag: v2.2.0
  - name: quay.io/k8scsi/csi-node-driver-registrar
    newTag: v1.3.0
  - name: hetznercloud/hcloud-csi-driver
    newTag: 1.5.3
  - name: quay.io/k8scsi/livenessprobe
    newTag: v2.2.0
